CREATE DATABASE `MV_app`;
CREATE DATABASE `MV_control`;
CREATE DATABASE `MV_pacientes`;
CREATE DATABASE `MV_sesiones`;
REVOKE ALL PRIVILEGES ON *.* FROM 'clientes'@'%'; REVOKE GRANT OPTION ON *.* FROM 'clientes'@'%'; GRANT SELECT, INSERT, UPDATE, DELETE, DROP, FILE ON *.* TO 'clientes'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;